homeassistant:
# Name of the location where Home Assistant is running
  name: Ostseebad Nienhagen
# Location required to calculate the time the sun rises and sets
  latitude: 54.154
  longitude: 11.946
# Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
# metric for Metric, imperial for Imperial
  unit_system: metric
# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin


#vernünftige Namen der Komponenten##
  customize: !include customize.yaml


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
 ignore:
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
logbook:
logger:
  default: warning

# Alte Events, States löschen
recorder:
  purge_days: 14

# Track the sun
sun:

# Sensoren 
sensor: !include sensor.yaml

# Gruppen/Tabs
group: !include groups.yaml


# Yeelights

light:
  - platform: yeelight
    devices:
      192.168.0.80:
        name: Wohnzimmer Licht
        transition: 350 
        use_music_mode: False
        save_on_change: True
      192.168.0.124:
        name: Romy Licht
        transition: 350
        use_music_mode: False
        save_on_change: True
      192.168.0.148:
        name: Bad Licht
        transition: 350
        use_music_mode: False
        save_on_change: True
      192.168.0.109:
        name: Speisesaal Licht
        transition: 350
        use_music_mode: False
        save_on_change: True

# F.Lux Lichtwärme an Uhrzeit anpassen
switch:
  platform: flux
  lights:
    - light.wohnzimmer
    - light.bad
    - light.speisesaal
  name: Fluxer
  start_time: '5:45'
  stop_time: '5:30'
  start_colortemp: 5000
  sunset_colortemp: 3400
  stop_colortemp: 2700
  disable_brightness_adjust: False
  mode: mired

media_player:
  - platform: kodi
    host: 192.168.0.157
    name: Kodi
    port: 80
    enable_websocket: false
  - platform: vlc
    name: VLC
scene:
  - name: Wohnzimmer normal
    entities:
        light.wohnzimmer_licht:
            state: on
            transition: 2
            brightness: 250
            xy_color: [ 0.4448, 0.4066 ]
        
  - name: Wohnzimmer dimmen
    entities:
        light.wohnzimmer_licht:
            state: on
            transition: 2
            brightness: 25
            xy_color: [ 0.5926, 0.3814 ]

automation:
  - alias: "Media player paused/stopped"
    trigger:
      - platform: state
        entity_id: media_player.kodi
        from: 'playing'
        to: 'idle'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: scene.turn_on
        entity_id: scene.wohnzimmer_normal
#      - service: switch.turn_on
#        entity_id: switch.fluxer
  - alias: "Balkon offen"
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d000153b0e1
        from: 'off'
        to: 'on'
    action:
      - service: light.turn_off
        entity_id: light.wohnzimmer_licht
  - alias: "Balkon geschlossen"
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d000153b0e1
        from: 'on'
        to: 'off'
    action:
      - service: light.turn_on
        entity_id: light.wohnzimmer_licht
  - alias: "Media player playing"
    trigger:
      - platform: state
        entity_id: media_player.kodi
        to: 'playing'
        from: 'idle'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: scene.turn_on
        entity_id: scene.wohnzimmer_dimmen
#      - service: switch.turn_off
#        entity_id: switch.fluxer

  - alias: "Nachtlicht bei Bewegung"
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d00010f859c
      from: 'no_motion'
      to: 'motion'
    action:
    - service: light.turn_on
      entity_id: light.gateway_light_f0b429cc315f
      data:
        rgb_color: [255,197,121]
        brightness: 155

  - alias: "Update Benachrichtigungen"
    trigger:
        platform: state
        entity_id: updater.updater
    action:
      service: notify.telegram
      data:
        message: 'Es gibt eine neue HASS-Version!'
  - alias: "Fluxer Start"
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: switch.turn_on
      entity_id:
        - switch.fluxer

#  - alias: "Schlafzimmer Feuchtigkeitsalarm aktivieren"
#    trigger:
#      - platform: template
#        value_template: '{{ states.sensor.humidity_158d00012914cb.state | int > 60 }}'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: device_tracker.stephansiphone
#          state: 'home'
#        - condition: time
#          after: '06:00:00'
#          before: '22:00:00'
#    action:
#      service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.schlafzimmer_feucht
#  - alias: "Schlafzimmer Temperaturalarm aktivieren"
#    trigger:
#      - platform: template
#        value_template: '{{ states.sensor.temperature_158d00012914cb.state | int < 17 }}'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: device_tracker.stephansiphone
#          state: 'home'
#        - condition: time
#          after: '06:00:00'
#          before: '22:00:00'
#    action:
#      service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.schlafzimmer_kalt
#  - alias: "Wohnzimmer Feuchtigkeitsalarm aktivieren"
#    trigger:
#      - platform: template
#        value_template: '{{ states.sensor.humidity_158d00011172f3.state | int > 60 }}'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: device_tracker.stephansiphone
#          state: 'home'
#        - condition: time
#          after: '06:00:00'
#          before: '22:00:00'
#    action:
#      service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.wohnzimmer_feucht
#  - alias: "Wohnzimmer Temperaturalarm aktivieren"
#    trigger:
#      - platform: template
#        value_template: '{{ states.sensor.temperature_158d00011172f3.state | int < 17 }}'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: device_tracker.stephansiphone
#          state: 'home'
#        - condition: time
#          after: '06:00:00'
#          before: '22:00:00'
#    action:
#      service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.wohnzimmer_kalt
#  - alias: "Bad Feuchtigkeitsalarm aktivieren"
#    trigger:
#      - platform: template
#        value_template: '{{ states.sensor.humidity_158d00012bf206.state | int > 69 }}'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: device_tracker.stephansiphone
#          state: 'home'
#        - condition: time
#          after: '06:00:00'
#          before: '22:00:00'
#    action:
#      service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.bad_feucht
#  - alias: "Bad Temperaturalarm aktivieren"
#    trigger:
#      - platform: template
#        value_template: '{{ states.sensor.temperature_158d00012bf206.state | int < 17 }}'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: device_tracker.stephansiphone
#          state: 'home'
#        - condition: time
#          after: '06:00:00'
#          before: '22:00:00'
#    action:
#      service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.bad_kalt
#  - alias: "Spielzimmer Feuchtigkeitsalarm aktivieren"
#    trigger:
#      - platform: template
#        value_template: '{{ states.sensor.humidity_158d0001100456.state | int > 60 }}'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: device_tracker.stephansiphone
#          state: 'home'
#        - condition: time
#          after: '06:00:00'
#          before: '22:00:00'
#    action:
#      service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.spielzimmer_feucht
#  - alias: "Spielzimmer Temperaturalarm aktivieren"
#    trigger:
#      - platform: template
#        value_template: '{{ states.sensor.temperature_158d0001100456.state | int < 17 }}'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: device_tracker.stephansiphone
#          state: 'home'
#        - condition: time
#          after: '06:00:00'
#          before: '22:00:00'
#    action:
#      service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.spielzimmer_kalt


##
## TelegramBot
##

notify:
  - name: Telegram
    platform: telegram
    api_key: 372241811:AAEjswt9XPBRX0MA86Fgw5-ICBWRn8tuqmE
    chat_id: 19976847
  - name: Telegram_Haushalt
    platform: telegram
    api_key: 372241811:AAEjswt9XPBRX0MA86Fgw5-ICBWRn8tuqmE
    chat_id: -204074268  


##
## Xiaomi Gateway
##

xiaomi:
  gateways:
    - sid: f0b429cc315f
      key: 4qmrkdu6abglo8zg

device_tracker:
  - platform: icloud
    username: regularj@pictor.uberspace.de
    password: !secret icloud
    account_name: Stephans iPhone
  - platform: nmap_tracker
    hosts: 192.168.0.1-255
    value_template: '{% if states.device_tracker.androide3c5daf46596c063home.state == "home"%} zu Hause {%- else -%} nicht zu Hause {%- endif -%}'
  - platform: owntracks

mqtt:
  broker: 95.143.172.207
  port: 62977

alert:
  romy_feuchtigkeit:
    name: Romys Zimmer müsste mal gelüftet werden!
    entity_id: binary_sensor.spielzimmer_feucht
    repeat: 60
    notifiers:
      - telegram_haushalt
  wohnzimmer_feuchtigkeit:
    name: Das Wohnzimmer müsste mal gelüftet werden!
    entity_id: binary_sensor.wohnzimmer_feucht
    repeat: 60
    notifiers:
      - telegram_haushalt
  bad_feuchtigkeit:
    name: Das Bad müsste mal gelüftet werden!
    entity_id: binary_sensor.bad_feucht
    repeat: 60
    notifiers:
      - telegram_haushalt
  schlafzimmer_feuchtigkeit:
    name: Das Schlafzimmer müsste mal gelüftet werden!
    entity_id: binary_sensor.schlafzimmer_feucht
    repeat: 60
    notifiers:
      - telegram_haushalt
  romy_temperatur:
    name: Niedrige Temperatur in Romys Zimmer!
    entity_id: binary_sensor.spielzimmer_kalt
    repeat: 60
    notifiers:
      - telegram_haushalt
  wohnzimmer_temperatur:
    name: Niedrige Temperatur im Wohnzimmer!
    entity_id: binary_sensor.wohnzimmer_kalt
    repeat: 60
    skip_first: true
    notifiers:
      - telegram_haushalt
  bad_temperatur:
    name: Niedrige Temperatur im Bad!
    entity_id: binary_sensor.bad_kalt
    repeat: 60
    skip_first: true
    notifiers:
      - telegram_haushalt
  schlafzimmer_temperatur:
    name: Niedrige Temperatur im Schlafzimmer!
    entity_id: binary_sensor.schlafzimmer_kalt
    repeat: 60
    skip_first: true
    notifiers:
      - telegram_haushalt

binary_sensor:
  - platform: command_line
    command: 'ls /home/pi/.homebridge/homebridge-status | grep -i "stephan_home" | wc -l'
    name: Stephan ist zu Hause
    payload_on: 1
    payload_off: 0
    scan_interval: 30
  - platform: iss
  - platform: template
    sensors:
      spielzimmer_feucht:
        value_template: '{{ states.sensor.humidity_158d0001100456.state | int > 60 }}'
        friendly_name: 'Romys Zimmer Luftfeuchte'
  - platform: template
    sensors:
      wohnzimmer_feucht:
        value_template: '{{ states.sensor.humidity_158d00011172f3.state | int > 60 }}'
        friendly_name: 'Wohnzimmer Luftfeuchte'
  - platform: template
    sensors:
      bad_feucht:
        value_template: '{{ states.sensor.humidity_158d00012bf206.state | int > 69 }}'
        friendly_name: 'Bad Luftfeuchte'
  - platform: template
    sensors:
      schlafzimmer_feucht: 
        value_template: '{{ states.sensor.humidity_158d00012914cb.state | int > 60 }}'
        friendly_name: 'Schlafzimmer Luftfeuchte'
  - platform: template
    sensors:
      spielzimmer_kalt:
        value_template: '{{ states.sensor.temperature_158d0001100456.state | int < 17 }}'
        friendly_name: 'Romys Zimmer Temperatur'
  - platform: template
    sensors:
      wohnzimmer_kalt:
        value_template: '{{ states.sensor.temperature_158d00011172f3.state | int < 17 }}'
        friendly_name: 'Wohnzimmer Temperatur'
  - platform: template
    sensors:
      bad_kalt:
        value_template: '{{ states.sensor.temperature_158d00012bf206.state | int < 17 }}'
        friendly_name: 'Bad Temperatur'
  - platform: template
    sensors:
      schlafzimmer_kalt:
        value_template: '{{ states.sensor.temperature_158d00012914cb.state | int < 17 }}'
        friendly_name: 'Schlafzimmer Temperatur'

ios:

tts:
  - platform: google
    language: 'de'

google:
  client_id: 44558772016-ni3uiijas046ihu81vdsecor4q7ofb9d.apps.googleusercontent.com 
  client_secret: m7vYHKNj4ZfpN5z8HckouJ-O

zone:
  name: Stephans Arbeit
  latitude: 54.1478358
  longitude: 11.892381
  icon: mdi:calendar-multiple 

zone 2:
  name: Jules Arbeit
  latitude: 54.152141
  longitude: 11.709278
  icon: mdi:calendar-multiple

zone 3:
  name: Tagesmutter
  latitude: 54.1635696
  longitude: 11.9659407
  icon: mdi:baby-buggy

panel_iframe:
  kodi:
    title: 'Kodi'
    url: 'http://192.168.0.157:80'
    icon: mdi:kodi

camera:
  - name: Stephan
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.stephansiphone.attributes.latitude }},{{ states.device_tracker.stephansiphone.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:S%7C{{ states.device_tracker.stephansiphone.attributes.latitude }},{{ states.device_tracker.stephansiphone.attributes.longitude }}
    limit_refetch_to_url_change: true
  - name: Jule
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.androide3c5daf46596c063home.attributes.latitude }},{{ states.device_tracker.androide3c5daf46596c063home.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:red%7Clabel:J%7C{{ states.device_tracker.androide3c5daf46596c063home.attributes.latitude }},{{ states.device_tracker.androide3c5daf46596c063home.attributes.longitude }}
    limit_refetch_to_url_change: true
  - name: Jules Arbeitshandy
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.androidf0f89b5be25f73echome.attributes.latitude }},{{ states.device_tracker.androidf0f89b5be25f73echome.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:red%7Clabel:JA%7C{{ states.device_tracker.androidf0f89b5be25f73echome.attributes.latitude }},{{ states.device_tracker.androidf0f89b5be25f73echome.attributes.longitude }}
    limit_refresh_to_url_change: true
  - name: OwnTracks
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.owntracks_paulus.attributes.latitude }},{{ states.device_tracker.owntracks.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:O%7C{{ states.device_tracker.owntracks.attributes.latitude }},{{ states.device_tracker.owntracks.attributes.longitude }}
    limit_refetch_to_url_change: true
