homeassistant:
# Name of the location where Home Assistant is running
  name: Ostseebad Nienhagen
# Location required to calculate the time the sun rises and sets
  latitude: 54.154
  longitude: 11.946
# Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
# metric for Metric, imperial for Imperial
  unit_system: metric
# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin


#vernünftige Namen der Komponenten##
  customize: !include customize.yaml


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
 ignore:
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
logger:
#  default: warning

# Alte Events, States löschen
recorder:
  purge_days: 14

# Track the sun
sun:


#sensor: !include sensor.yaml
sensor:
  - platform: template
    sensors:
      privat:
        friendly_name: 'Privat'
        value_template: '{{ states.calendar.stephaneckermanngooglemailcom.attributes.message}} am {{ as_timestamp(states.calendar.stephaneckermanngooglemailcom.attributes.start_time) | timestamp_custom("%d.%m.%Y, um %H:%M",True) }} Uhr.'
  - platform: template
    sensors:
      contacts:
        friendly_name: 'Kontakte'
        value_template: '{{ states.calendar.contacts.attributes.message }}'
  - platform: template
    sensors:
      geburtstagskalender:
        friendly_name: 'Geburtstage'
        value_template: '{{ states.calendar.geburtstagskalender.attributes.message }} hat am {{ as_timestamp(states.calendar.geburtstagskalender.attributes.start_time) | timestamp_custom("%d.%m.",True) }} Geburtstag'
#  - platform: template
#    sensors:
#      friends_geburtstage:
#        friendly_name: 'Geburtstage'
#        value_template: '{{ states.calendar.friends_birthdays.attributes.message }} ist am {{ as_timestamp(states.calendar.friends_birthdays.attributes.start_time) | timestamp_custom("%d.%m.",True) }}'
  - platform: template
    sensors:
      feiertage:
        friendly_name: 'Feiertage'
        value_template: '{{ as_timestamp(states.calendar.feiertage_in_deutschland.attributes.start_time) | timestamp_custom("Am %d.%m.",True) }} ist {{ states.calendar.feiertage_in_deutschland.attributes.message }}'
  - platform: systemmonitor
    resources:
      - type: since_last_boot
  - platform: template
    sensors:
      since_last_boot_templated:
        value_template: >-
          {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
          {%- set count = slb | length -%}
          {%- set hms = slb[count - 1] -%}
          {%- set hms_trimmed = hms.split('.')[0] -%}
          {%- set hms_split = hms_trimmed.split(':') -%}
          {%- set hours = hms_split[0] | int -%}
          {%- set minutes = hms_split[1] | int -%}
          {%- set seconds = hms_split[2] | int -%}
           {%- if count == 3 -%}
            {{ slb[0] ~ ' ' ~ slb[1] ~ ' ' }}
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if hours == 1 -%}
              1 Stunde
            {%- else -%}
              {{ hours }} Stunden
            {%- endif -%}
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ', ' }}
            {%- endif -%}
            {%- if minutes == 1 -%}
              1 Minuten
            {%- else -%}
              {{ minutes }} Minuten
            {%- endif -%}
          {%- endif -%}
          {%- if seconds > 0 -%}
            {%- if hours > 0 or minutes > 0 -%}
              {{ ', ' }}
            {%- endif -%}
            {%- if seconds == 1 -%}
              1 Sekunde
            {%- else -%}
              {{ seconds }} Sekunden
            {%- endif -%}
          {%- endif -%}
  - platform: nzbget
    host: 192.168.0.157
    port: 5678
    username: nzbget
    password: !secret nzbget
    monitored_variables:
      - remaining_size
      - download_rate
      - download_paused
  - platform: template
    sensors:
      battery_stephansiphone:
        unit_of_measurement: '%'
        value_template: >-
            {%- if states.device_tracker.stephansiphone.attributes.battery %}
                {{ states.device_tracker.stephansiphone.attributes.battery|round }}
            {% else %}
                {{ states.sensor.battery_stephansiphone.state }}
            {%- endif %}
        icon_template: '{%- if is_state("sensor.battery_stephansiphone", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.stephansiphone", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.stephansiphone.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.stephansiphone.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.stephansiphone.attributes.battery|float / 10)|round*10}}{%- endif %}'
      battery_applewatch:
        unit_of_measurement: '%'
        value_template: >-
            {%- if states.device_tracker.apple_watchvonstephan.attributes.battery %}
                {{ states.device_tracker.apple_watchvonstephan.attributes.battery|round }}
            {% else %}
                {{ states.sensor.battery_apple_watchvonstephan.state }}
            {%- endif %}
        icon_template: '{%- if is_state("sensor.battery_apple_watchvonstephan", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.apple_watchvonstephan", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.apple_watchvonstephan.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.apple_watchvonstephan.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.apple_watchvonstephan.attributes.battery|float / 10)|round*10}}{%- endif %}'
      battery_balkon:
        value_template: '{{ states.binary_sensor.door_window_sensor_158d000153b0e1.attributes.battery_level }} %'
        friendly_name: Balkontür
        icon_template: '
        {%- if is_state("binary_sensor.door_window_sensor_158d000153b0e1", "unknown") %}
           mdi:battery-unknown
        {%- elif  states.binary_sensor.door_window_sensor_158d000153b0e1.attributes.battery_level <= 5 %}
           mdi:battery-outline
        {%- elif states.binary_sensor.door_window_sensor_158d000153b0e1.attributes.battery_level >= 95 %}
           mdi:battery
        {% else %}
           mdi:battery-{{(states.binary_sensor.door_window_sensor_158d000153b0e1.attributes.battery_level|float / 10)|round*10}}
        {% if states.binary_sensor.door_window_sensor_158d000153b0e1.state == "on"%} Offen {%- else -%} Geschlossen {%- endif -%}
        {%- endif %}'
      battery_hygro_wohnzimmer:
        value_template: '{{ states.sensor.temperature_158d00011172f3.attributes.battery_level }} %'    
        friendly_name: Hygrometer Wohnzimmer
        icon_template: '
        {%- if is_state("sensor.temperature_158d00011172f3", "unknown") %}
           mdi:battery-unknown
        {%- elif  states.sensor.temperature_158d00011172f3.attributes.battery_level <= 5 %}
           mdi:battery-outline
        {%- elif states.sensor.temperature_158d00011172f3.attributes.battery_level >= 95 %}
           mdi:battery
        {% else %}
           mdi:battery-{{(states.sensor.temperature_158d00011172f3.attributes.battery_level|float / 10)|round*10}}
        {%- endif %}'
      battery_hygro_romy:
        value_template: '{{ states.sensor.temperature_158d0001100456.attributes.battery_level }} %'
        friendly_name: Hygrometer Romys Zimmer
        icon_template: '
        {%- if is_state("sensor.temperature_158d0001100456", "unknown") %}
           mdi:battery-unknown
        {%- elif  states.sensor.temperature_158d0001100456.attributes.battery_level <= 5 %}
           mdi:battery-outline
        {%- elif states.sensor.temperature_158d0001100456.attributes.battery_level >= 95 %}
           mdi:battery
        {% else %}
           mdi:battery-{{(states.sensor.temperature_158d0001100456.attributes.battery_level|float / 10)|round*10}}
        {%- endif %}'
      battery_hygro_bad:
        value_template: '{{ states.sensor.temperature_158d00012bf206.attributes.battery_level }} %'
        friendly_name: Hygrometer Badezimmer
        icon_template: '
        {%- if is_state("sensor.temperature_158d00012bf206", "unknown") %}
           mdi:battery-unknown
        {%- elif  states.sensor.temperature_158d00012bf206.attributes.battery_level <= 5 %}
           mdi:battery-outline
        {%- elif states.sensor.temperature_158d00012bf206.attributes.battery_level >= 95 %}
           mdi:battery
        {% else %}
           mdi:battery-{{(states.sensor.temperature_158d00012bf206.attributes.battery_level|float / 10)|round*10}}
        {%- endif %}'
      battery_hygro_schlafzimmer:
        value_template: '{{ states.sensor.temperature_158d00012914cb.attributes.battery_level }} %'
        friendly_name: Hygrometer Schlafzimmer
        icon_template: '
        {%- if is_state("sensor.temperature_158d00012914cb", "unknown") %}
           mdi:battery-unknown
        {%- elif  states.sensor.temperature_158d00012914cb.attributes.battery_level <= 5 %}
           mdi:battery-outline
        {%- elif states.sensor.temperature_158d00012914cb.attributes.battery_level >= 95 %}
           mdi:battery
        {% else %}
           mdi:battery-{{(states.sensor.temperature_158d00012914cb.attributes.battery_level|float / 10)|round*10}}
        {%- endif %}'
      battery_bewegungsmelder:
        value_template: '{{ states.binary_sensor.motion_sensor_158d00010f859c.attributes.battery_level }} %'
        friendly_name: Bewegungsmelder Flur
        icon_template: '
        {%- if is_state("binary_sensor.motion_sensor_158d00010f859c", "unknown") %}
           mdi:battery-unknown
        {%- elif  states.binary_sensor.motion_sensor_158d00010f859c.attributes.battery_level <= 5 %}
           mdi:battery-outline
        {%- elif states.binary_sensor.motion_sensor_158d00010f859c.attributes.battery_level >= 95 %}
           mdi:battery
        {% else %}
           mdi:battery-{{(states.binary_sensor.motion_sensor_158d00010f859c.attributes.battery_level|float / 10)|round*10}}
        {%- endif %}'
  - platform: sonarr
    api_key: a3b159ca37664be78233a86afaf9602d
    host: 192.168.0.157
    port: 8989
    monitored_conditions:
      - upcoming
      - wanted
      - queue
      - diskspace
    days: 7
  - platform: darksky
    language: de
    api_key: 61beaf4f6ab875c7912c9ccfb6054fc4
    update_interval: '00:05'
    monitored_conditions:
       - summary
       - precip_type
       - precip_intensity
       - precip_probability
       - temperature
       - apparent_temperature
       - dew_point
       - wind_speed
       - wind_bearing
       - cloud_cover
       - humidity
       - pressure
       - visibility
       - hourly_summary
       - daily_summary
       - temperature_max
       - temperature_min

group: !include groups.yaml


# Yeelights

light:
  - platform: yeelight
    devices:
      192.168.0.80:
        name: Wohnzimmer Licht
        transition: 350 
        use_music_mode: False
        save_on_change: True
      192.168.0.124:
        name: Romy Licht
        transition: 350
        use_music_mode: False
        save_on_change: True
      192.168.0.148:
        name: Bad Licht
        transition: 350
        use_music_mode: False
        save_on_change: True
      192.168.0.109:
        name: Speisesaal Licht
        transition: 350
        use_music_mode: False
        save_on_change: True

# F.Lux Lichtwärme an Uhrzeit anpassen
switch:
  platform: flux
  lights:
    - light.wohnzimmer
    - light.bad
    - light.speisesaal
  name: Fluxer
  start_time: '5:30'
  stop_time: '23:59'
  start_colortemp: 5000
  sunset_colortemp: 3400
  stop_colortemp: 2700
  disable_brightness_adjust: False
  mode: mired

media_player:
  - platform: kodi
    host: 192.168.0.157
    name: Kodi
    port: 80
    enable_websocket: false

scene:
  - name: Wohnzimmer normal
    entities:
        light.wohnzimmer_licht:
            state: on
            transition: 2
            brightness: 250
            xy_color: [ 0.4448, 0.4066 ]
        
  - name: Wohnzimmer dimmen
    entities:
        light.wohnzimmer_licht:
            state: on
            transition: 2
            brightness: 25
            xy_color: [ 0.5926, 0.3814 ]

automation:
  - alias: "Media player paused/stopped"
    trigger:
      - platform: state
        entity_id: media_player.kodi
        from: 'playing'
        to: 'idle'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
        service: scene.turn_on
        entity_id: scene.wohnzimmer_normal
#      - service: switch.turn_on
#        entity_id: switch.flux
  - alias: "Balkon offen"
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d000153b0e1
        from: 'off'
        to: 'on'
    action:
      - service: light.turn_off
        entity_id: light.wohnzimmer_licht
  - alias: "Balkon geschlossen"
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d000153b0e1
        from: 'on'
        to: 'off'
    action:
      - service: light.turn_on
        entity_id: light.wohnzimmer_licht
  - alias: "Media player playing"
    trigger:
      - platform: state
        entity_id: media_player.kodi
        to: 'playing'
        from: 'idle'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
        service: scene.turn_on
        entity_id: scene.wohnzimmer_dimmen
#      - service: switch.turn_off
#        entity_id: switch.flux

  - alias: "Nachtlicht bei Bewegung"
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d00010f859c
      from: 'no_motion'
      to: 'motion'
    action:
    - service: light.turn_on
      entity_id: light.gateway_light_f0b429cc315f
      data:
        rgb_color: [255,197,121]
        brightness: 155

  - alias: "Update Benachrichtigungen"
    trigger:
        platform: state
        entity_id: updater.updater
    action:
      service: notify.telegram
      data:
        message: 'Es gibt eine neue HASS-Version!'


##
## TelegramBot
##

notify:
  - name: Telegram
    platform: telegram
    api_key: 372241811:AAEjswt9XPBRX0MA86Fgw5-ICBWRn8tuqmE
    chat_id: 19976847
  - name: Telegram_Haushalt
    platform: telegram
    api_key: 372241811:AAEjswt9XPBRX0MA86Fgw5-ICBWRn8tuqmE
    chat_id: -204074268  


##
## Xiaomi Gateway
##

xiaomi:
  gateways:
    - sid: f0b429cc315f
      key: 4qmrkdu6abglo8zg

device_tracker:
  - platform: icloud
    username: regularj@pictor.uberspace.de
    password: !secret icloud
    account_name: Stephans iPhone

alert:
  romy_feuchtigkeit:
    name: Romys Zimmer müsste mal gelüftet werden!
    entity_id: binary_sensor.romy_zimmer_feucht
    repeat: 30
    notifiers:
      - telegram_haushalt
  wohnzimmer_feuchtigkeit:
    name: Das Wohnzimmer müsste mal gelüftet werden!
    entity_id: binary_sensor.wohnzimmer_feucht
    repeat: 30
    notifiers:
      - telegram_haushalt
  bad_feuchtigkeit:
    name: Das Bad müsste mal gelüftet werden!
    entity_id: binary_sensor.bad_feucht
    repeat: 30
    notifiers:
      - telegram_haushalt
  schlafzimmer_feuchtigkeit:
    name: Das Schlafzimmer müsste mal gelüftet werden!
    entity_id: binary_sensor.schlafzimmer_feucht
    repeat: 30
    notifiers:
      - telegram_haushalt
  romy_temperatur:
    name: Niedrige Temperatur in Romys Zimmer!
    entity_id: binary_sensor.romy_zimmer_kalt
    repeat: 30
    skip_first: True
    notifiers:
      - telegram_haushalt
  wohnzimmer_temperatur:
    name: Niedrige Temperatur im Wohnzimmer!
    entity_id: binary_sensor.wohnzimmer_kalt
    skip_first: True
    repeat: 30
    notifiers:
      - telegram_haushalt
  bad_temperatur:
    name: Niedrige Temperatur im Bad!
    entity_id: binary_sensor.bad_kalt
    skip_first: True
    repeat: 30
    notifiers:
      - telegram_haushalt
  schlafzimmer_temperatur:
    name: Niedrige Temperatur im Schlafzimmer!
    entity_id: binary_sensor.schlafzimmer_kalt
    repeat: 30
    skip_first: True
    notifiers:
      - telegram_haushalt

binary_sensor:
  - platform: iss
  - platform: template
    sensors:
      romy_zimmer_feucht:
        value_template: '{{ states.sensor.humidity_158d0001100456.state | int > 60 }}'
        friendly_name: 'Romys Zimmer Luftfeuchte'
  - platform: template
    sensors:
      wohnzimmer_feucht:
        value_template: '{{ states.sensor.humidity_158d00011172f3.state | int > 60 }}'
        friendly_name: 'Wohnzimmer Luftfeuchte'
  - platform: template
    sensors:
      bad_feucht:
        value_template: '{{ states.sensor.humidity_158d00012bf206.state | int > 69 }}'
        friendly_name: 'Bad Luftfeuchte'
  - platform: template
    sensors:
      schlafzimmer_feucht: 
        value_template: '{{ states.sensor.humidity_158d00012914cb.state | int > 60 }}'
        friendly_name: 'Schlafzimmer Luftfeuchte'
  - platform: template
    sensors:
      romy_zimmer_kalt:
        value_template: '{{ states.sensor.temperature_158d0001100456.state | int < 17 }}'
        friendly_name: 'Romys Zimmer Temperatur'
  - platform: template
    sensors:
      wohnzimmer_kalt:
        value_template: '{{ states.sensor.temperature_158d00011172f3.state | int < 17 }}'
        friendly_name: 'Wohnzimmer Temperatur'
  - platform: template
    sensors:
      bad_kalt:
        value_template: '{{ states.sensor.temperature_158d00012bf206.state | int < 17 }}'
        friendly_name: 'Bad Temperatur'
  - platform: template
    sensors:
      schlafzimmer_kalt:
        value_template: '{{ states.sensor.temperature_158d00012914cb.state | int < 17 }}'
        friendly_name: 'Schlafzimmer Temperatur'

ios:

google:
  client_id: 44558772016-ni3uiijas046ihu81vdsecor4q7ofb9d.apps.googleusercontent.com 
  client_secret: m7vYHKNj4ZfpN5z8HckouJ-O
